Fix `main` in package.json
Some tools don't work if the `main` entry does not have a file extension, for example TypeScript:

```js
error TS2307: Cannot find module 'yar'.
```